


-- 10. Crear tablas EMPLE y DEPART
CREATE TABLE EMPLE (
    EMP_NO NUMBER,
    APELLIDO VARCHAR2,
    OFICIO VARCHAR2,
    DIR VARCHAR2,
    FECHA_ALTA DATE,
    SALARIO NUMBER,
    COMISION NUMBER,
    DEPT_NO NUMBER
);
CREATE TABLE DEPART (
    DEPT_NO NUMBER,
    DNOMBRE VARCHAR2,
    LOC VARCHAR2
);
