

-- BD_UD03-EjerciciosCreateAlter1

-- 1. Creación de tablas EMPLEADO y DEPARTAMENTO
CREATE TABLE empleado (
    NUMEMPLEADO NUMBER(4),
    NOMBRE VARCHAR2(10),
    APELLIDO VARCHAR2(10),
    OFICIO VARCHAR2(10),
    DIR NUMBER(4),
    FECALTA DATE,
    SALARIO NUMBER(7) NOT NULL,
    COMISION NUMBER(7),
    NUMDEPARTAMENTO NUMBER(2),
    CONSTRAINT NUMEROEMPLEADO_PK PRIMARY KEY(NUMEMPLEADO),
    CONSTRAINT DEPARTAMENTO_EMPLEADO FOREIGN KEY(NUMDEPARTAMENTO) REFERENCES departamento(NUMDEPARTAMENTO)
);

CREATE TABLE departamento (
    NUMDEPARTAMENTO NUMBER(2),
    NOMBREDEPARTAMENTO VARCHAR2(14),
    LOC VARCHAR2(14),
    CONSTRAINT NUMDEPARTAMENTO_PK PRIMARY KEY(NUMDEPARTAMENTO)
);
