
-- 6. Crear tablas FABRICANTES y ARTICULOS
CREATE TABLE FABRICANTES (
    COD_FABRICANTE NUMBER(3) PRIMARY KEY,
    NOMBRE VARCHAR2(15) CHECK (NOMBRE = UPPER(NOMBRE)),
    PAIS VARCHAR2(15) CHECK (PAIS = UPPER(PAIS))
);



CREATE TABLE ARTICULOS (
    ARTICULO VARCHAR2(20),
    COD_FABRICANTE NUMBER(3),
    PESO NUMBER CHECK (PESO > 0),
    CATEGORIA VARCHAR2 DEFAULT 'Primera',
    PRECIO_VENTA NUMBER CHECK (PRECIO_VENTA > 0),
    PRECIO_COSTO NUMBER CHECK (PRECIO_COSTO > 0),
    EXISTENCIAS NUMBER(65),
    CONSTRAINT losprimeros4campos_pk PRIMARY KEY (ARTICULO, COD_FABRICANTE, PESO, CATEGORIA),
    CONSTRAINT cod_fabricante_fk FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES(COD_FABRICANTE)
);
