

-- UT3_5-CiudadesIdiomasInstitutos
-- 1. Crear tabla INSTITUTOS
CREATE TABLE INSTITUTOS (
    CODIGO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    CIUDAD NUMBER NOT NULL,
    TIPO VARCHAR2(100),
    WEB VARCHAR2(100),
    EMAIL VARCHAR2(100) NOT NULL,
    TELEFONO NUMBER(12)
);
