
-- 3. Creación de la tabla ALUMNOS
CREATE TABLE ALUMNOS (
    NRE NUMBER PRIMARY KEY,
    APELLIDOS VARCHAR2(50) NOT NULL,
    NOMBRE VARCHAR2(30) NOT NULL,
    FECHANAC DATE,
    COUNTRYCODE VARCHAR2(3) NOT NULL,
    LANGUAGE VARCHAR2(30) NOT NULL
);
