
-- 4. Inserciones en las tablas EMPLEADO y DEPARTAMENTO
INSERT INTO departamento (NUMDEPARTAMENTO, NOMBREDEPARTAMENTO, CIUDAD, JEFE) VALUES (valor1, valor2, valor3, valor4);
INSERT INTO empleado (NUMEMPLEADO, NOMBRE, APELLIDO, OFICIO, DIRECCION, FECALTA, SALARIO, COMISION, NUMDEPARTAMENTO) VALUES (valor1, valor2, valor3, valor4, valor5, valor6, valor7, valor8, valor9);