

-- UT4.2_ConsultasEmpleadosDepartamentos
-- Modificaciones en las tablas EMPLEADOS y DEPARTAMENTOS
ALTER TABLE EMPLEADOS ADD (DNI VARCHAR2(9), PAIS VARCHAR2(20), CIUDAD VARCHAR2(20));
ALTER TABLE DEPARTAMENTOS ADD (NUMEMPLEADO_JEFE_DPTO NUMBER(20));

-- Inserciones en las tablas EMPLEADOS y DEPARTAMENTOS
-- Aquí van las instrucciones INSERT INTO para EMPLEADOS y DEPARTAMENTOS...