
-- 5. Regla de integridad para la tabla ALUMNOS
ALTER TABLE ALUMNOS ADD CONSTRAINT COUNTRYCODE_LANGUAGE_EJERC5 FOREIGN KEY (COUNTRYCODE, LANGUAGE) REFERENCES COUNTRYLANGUAGE (COUNTRY_CODE, LANGUAGE) ON DELETE CASCADE;
