
-- 2. Modificaciones en la tabla EMPLEADO
ALTER TABLE EMPLEADO RENAME COLUMN DIR TO DIRECCION;
ALTER TABLE EMPLEADO MODIFY APELLIDO VARCHAR2(20);
ALTER TABLE EMPLEADO MODIFY DIRECCION VARCHAR2(60);
ALTER TABLE EMPLEADO ADD DNI VARCHAR2(20);
ALTER TABLE EMPLEADO DROP CONSTRAINT NUMEROEMPLEADO_PK;
ALTER TABLE EMPLEADO ADD CONSTRAINT NUMEMPLEADO_DNI_PK PRIMARY KEY(DNI, NUMEMPLEADO);
ALTER TABLE EMPLEADO ADD PAIS VARCHAR2(20) DEFAULT 'ESPAÑA';
ALTER TABLE EMPLEADO ADD CIUDAD VARCHAR2(20);
ALTER TABLE EMPLEADO MODIFY FECALTA DATE DEFAULT SYSDATE;
ALTER TABLE EMPLEADO MODIFY SALARIO NUMBER(10,2);
ALTER TABLE EMPLEADO MODIFY COMISION NUMBER(10,2);
