
-- 4. Crear tabla EJEMPLO4
CREATE TABLE EJEMPLO4 (
    DNI NUMBER(10) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    EDAD NUMBER(2) CHECK (EDAD BETWEEN 5 AND 20),
    CURSO NUMBER(1) CHECK (CURSO IN (1, 2, 3))
);
